version: '3.8'

services:
  ms-sql: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: ms-sql
    restart: always
    ports: 
      - 1433:1433
    environment:
      - SA_PASSWORD=tXmYrAzB3D
      - ACCEPT_EULA=Y
      - SQL_PID=Developer
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
