services:
  postgres-sql:
    image: postgres
    container_name: postgres_sql_container
    ports:
      - ${POSTGRES_SQL_PORT}:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql

volumes:
  pg-data:
